### PR TITLE
Updated maven site plugin version and logos

### PR DESCRIPTION
**Pull request by ingokegel**
After https://github.com/sonatype/install4j-support/pull/37 a site update is advisable, because the new parameters are quite important, see #30

### CODE REVIEW

**Comment by jdillon** [comment]
was there any reason for the bytecode level change?  its probably fine, and time to generally update to a more recent basis?

**Comment by jdillon** [comment]
why was `src/site/resources/images/google-analytics.png` removed?

**Comment by ingokegel** [comment]
> was there any reason for the bytecode level change? its probably fine, and time to generally update to a more recent basis?

I updated it while trying to compile with Java 11, which does not support the 1.5 target anymore.

>why was src/site/resources/images/google-analytics.png removed?

Sorry about that, I actually meant to update the logo, but something went wrong, I'll add it again on Monday.

**Comment by jdillon** [comment]
@ingokegel I'll just update the image, this project probably needs a bit of love to update all the various bits to modern deps, not sure I'll have time to do that any time soon though.

**Pull request closed without merging**
